### ISSUE TITLE
dmplay couldn't load band

### ISSUE THREAD

**Issue by MaKiPL** [frabert/libdmusic#18]
Tried using the latest release with Final Fantasy VIII DirectMusic 6 SGT and DLS. Example output:
```

.\dmplay.exe -d 3 -s 96000 "D:\SteamLibrary\steamapps\common\FINAL FANTASY VIII\Data\Music\dmusic\013s-battle2.sgt"
Opening audio device...  done.
Loading segment... done.
Start playback...  Cannot play segment. Couldn't load band: FF8.dlsRendering started. Insert the next segment to be played, or 'exit' to end playback.
```

dmrender.exe produces one minute RIFF WAVe file with NULL content of 5292044 bytes.
dls2sf.exe produces no errors, however no files whatsoever

When implementing casual IDirectSound it handles the files without any hassle (but on Windows of course). It looks like your library would be finally a way of providing an access to music playback on Unix systems

**Comment by frabert** [comment]
Yes directmusic playback on Unix (and non legacy windows) systems is indeed the eventual scope of the library :)

Does the directory containing the `sgt` file also contain the `dls` files? If not, could you try running dmplay from the directory where the dls files are, pointing at the sgt?

Regarding dls2sf, can you show how it was invoked? It expects DLS files as input, not segments

EDIT: Actually I think I understand your issue: dmplay needs to be run from the directory containing the Sgt/DLS files currently, you seem to be running it from the build directory

**Comment by MaKiPL** [comment]
I've copied the dmplay and dmrender executables over the catalogue that contains both sgt and dls files. Error `Couldn't load band: FF8.dls` no longer appears, yet no sound is produced. On dmrender the same behaviour- null 5292044 bytes with RIFF header

**Comment by frabert** [comment]
Unfortunately I don't have a copy of the game handy, so I can't currently investigate this further... Does `dls2sf` work, in the mean time?

**Comment by MaKiPL** [comment]
Yes, putting -o parameter outputs the file normally. It has valid SoundBank header. 
I'll fork the code and debug it soon- I'll see why it doesn't seem to get through

**Comment by frabert** [comment]
Apparently, the issue is that FFVIII doesn't use Style files, instead embedding all sequences inside segments. This is something I had not encountered yet, I will see what can be done

**Comment by frabert** [comment]
I've pushed some commits on the https://github.com/frabert/libdmusic/tree/fix/ffviii branch, it now loads "something", basically some notes are played, but they are not using the correct instruments. Also level curves are missing, but it's a start I guess

**Comment by frabert** [comment]
@MaKiPL The files are (partially) working using one of the [latest artifacts](https://ci.appveyor.com/project/frabert/libdmusic/build/job/27spn503v5fo564s/artifacts) 

You need to use a GM DLS set, though. Windows ships one by default in `C:\Windows\system32\drivers\gm.dls`, you can use it this way:

    dmplay.exe --gm=C:/Windows/system32/drivers/gm.dls 000s-lose.sgt

On other platforms, you could use any kind of GeneralMidi SF2 set, instead of a DLS. I've only added the DLS loading as a PoC

EDIT: I see from your profile that you are re-implementing the FFVIII engine in C#. Personally, I'd reccommend the following strategy:
the music files from this particular game are basically MIDI files, as they do not use any of the features from DirectMusic. Because of this, I'd implement an ad-hoc parser for the limited subset of the SGT files in C#, and then wait for [fluidsynth to add support for DLS file loading](https://github.com/FluidSynth/fluidsynth/pull/493). Fluidsynth provides a C interface, while libdmusic (currently) does not, so interfacing it with C# is going to be much easier, and will also provide better rendering quality.

For documentation on the SGT file format, I used http://doc.51windows.net/Directx9_SDK/ (warning: the site is prone to "going down" and is quite slow, I personally downloaded a full copy of the parts I needed using wget)

**Comment by MaKiPL** [comment]
Thank you for the information- I completed my parser, indeed- it's just a casual MIDI sequence. It has real MIDI status (in my game example there's only one: NoteOn) with sequence absolute time, duration and all the needed data about instruments and chords. Looks like NoteOff is sent as soon as duration runs off.
